### ISSUE TITLE
Contact?

### ISSUE THREAD

**Issue by vazub** [climent/atreyu#1]
Hi climent,

Is there a way to reach out to you by chat/email/socialnet to ask some questions about atreyu keyboard? I would be interested in doing a build out of provided pcb's, but some things there are not entirely clear for me. Thanks!

**Comment by climent** [comment]
You can ask here, for example.

**Comment by climent** [comment]
Also, I am on several discords, like https://discord.gg/REsexBS6 under `Jesus Climent#0296`
