### ISSUE TITLE
gerbers files for V2 (none-choc)

### ISSUE THREAD

**Issue by maxyurk** [climent/atreyu#2]
Hi

First of all I'd like to thank you for this awesome open source keyboard.
I'm interested in building one.
My ask is if it would be possible to include the gerbers for the V2 under the sources/releases. I'm not experienced with KiCad and when I tried to create them I got an issue I couldn't resolve on my own.

Also if you're interested I can help out creating a github page for this project. I noticed a stale branch for it in the repo. https://docusaurus.io/ is a pretty good option I'm familiar with.

Thanks in advance.

**Comment by climent** [comment]
Gerber files for v2 have been added to the repo. Enjoy!

**Comment by maxyurk** [comment]
Thank you. It turned out great. Really happy with it.
![maxim](https://github.com/climent/atreyu/assets/28229974/00deb95b-7463-45e7-b96a-62653004bb0b)

**Comment by climent** [comment]
Looks really nice! Hope you enjoy it!
